### ISSUE TITLE
Finish implimenting the Sub9 model

### ISSUE THREAD

**Issue by MarshallRawson** [uf-mil/mil#240]
There is currently a bug with sub9 urdf that causes the odometry_estimator node to spit out nothing but nans. checkout `sub9-model` branch to see what I am talking about

**Comment by colefisher1** [comment]
After reading through your commit and testing sub9 locally, I was able to pinpoint the exact line causing the error to line 20 in the sub9.urdf:
`<inertia ixx="0.4674" ixy="-0.003" ixz="0.02" iyy="0.983" iyz="-0.0003" izz="1.197" />`

I found that removing or commenting out this line from the urdf fixed the nan issue. The source of the error is almost definitely one or multiple data values in the inertia matrix. 

See the link below:
 https://answers.ros.org/question/224380/nan-value-after-changing-inertia-matrix/

**Comment by MechAnger** [comment]
Found an exporter from direct solidworks to URDF that creates all the configs and launch files with ability to edit the origin, inertia matrices, meshed,textures and more that might solve this issue in the future since we do not have to input those infos anymore and it will be automatically generated. Already tried with other assemblies and it seems to be working in gazebo and rviz.

http://wiki.ros.org/sw_urdf_exporter

**Comment by cbrxyz** [comment]
Fixed
