### ISSUE TITLE
Test issue for InvestiGator

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/mil#758]
Oh no! This issue has definitely been opened by someone who is not part of the uf-mil organization!

Sounds like someone needs to chomp on this one...

**Comment by uf-mil-investigator** [comment]
@Object, thank you for your interested in the projects being worked on at the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

Unfortunately, at this time, we are unable to accept contributions from users outside of our organization for this repository. We thank you for your interest!

_If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._

**Comment by uf-mil-investigator** [comment]
@octocat, thank you for your interested in the projects being worked on at the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

Unfortunately, at this time, we are unable to accept contributions from users outside of our organization for this repository. We thank you for your interest!

_If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._

**Comment by uf-mil-investigator** [comment]
@cbrxyz, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

_If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._

**Comment by uf-mil-investigator** [comment]
@cbrxyz, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

_If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._

**Comment by uf-mil-investigator** [comment]
@cbrxyz, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

_If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._

**Comment by uf-mil-investigator** [comment]
@cbrxyz, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

_If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._

**Comment by uf-mil-investigator** [comment]
@cbrxyz, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

_If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._

**Comment by uf-mil-investigator** [comment]
@cbrxyz, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

_If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._

**Comment by uf-mil-investigator** [comment]
@cbrxyz, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

_If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._

**Comment by uf-mil-investigator** [comment]
@cbrxyz, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

_If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._

**Comment by uf-mil-investigator** [comment]
@cbrxyz, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

    Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

    _If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._

**Comment by uf-mil-investigator** [comment]
@cbrxyz, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

  Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

  _If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._

**Comment by uf-mil-investigator** [comment]
@cbrxyz, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

  Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

  _If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._
