### ISSUE TITLE
VRX documentation contains a broken link

### ISSUE THREAD

**Issue by kawaiiPlat** [uf-mil/mil#810]
![image](https://user-images.githubusercontent.com/50600614/184786858-2104d52f-644b-43ce-9f9e-149228cee373.png)
In [this page](https://uf-mil.github.io/docs/navigator/vrx.html) there is a broken link in the warning at the top. to resolve, make this link an actual link and not just some text.

**Comment by PrajwalBorkar** [comment]
I'm trying to work on this. But due to not having enough knowledge on .rst files,I'm unable to add the link for that directory. Any suggestions would be helpful.

**Comment by uf-mil-investigator** [comment]
@PrajwalBorkar, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

  Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

  _If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._
